import { useState, useRef } from "react";
import { C, fm } from "../theme";
import { Z, SvgIc } from "../icons";
import { Btn, Av, Hdr, Bdg, Inp, TxR, Scroll, MenuRow } from "../components";
import { MEM, CIR, MSGS, WALLETS } from "../data";

function CircleDetail({go,cid}){const c=CIR.find(x=>x.id===cid)||CIR[0];const[tab,setTab]=useState("m");const paid=MEM.filter(m=>m.ok).length;
return <Scroll><Hdr title={c.name} onBack={()=>go("back")}/>
<div style={{background:C.card,borderRadius:24,padding:20,border:`1px solid ${C.brd}`,marginBottom:16,boxShadow:C.sh}}>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><div><div style={{fontSize:12,color:C.t3}}>Cagnotte</div><div style={{fontSize:26,fontWeight:800,color:C.t0}}>{fm(c.tot)} <span style={{fontSize:13,color:C.t3}}>FCFA</span></div></div><div style={{textAlign:"right"}}><div style={{fontSize:12,color:C.t3}}>Par tour</div><div style={{fontSize:18,fontWeight:700,color:C.gold}}>{fm(c.amt)} F</div></div></div>
<div style={{background:C.bg,borderRadius:5,height:8,overflow:"hidden",marginBottom:8}}><div style={{width:`${c.prog}%`,height:"100%",background:`linear-gradient(90deg,${C.blue},${C.gold})`,borderRadius:5}}/></div>
<div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontSize:11,color:C.t3}}>Collecté: {c.prog}%</span><span style={{fontSize:11,color:C.t3}}>Prochain: <span style={{fontWeight:700,color:C.gold}}>{c.next}</span></span></div></div>
{/* Actions */}
<div style={{display:"flex",gap:6,marginBottom:8,flexWrap:"wrap"}}>{[{l:"Cotiser",ic:Z.up,s:"contribute"},{l:"Chat",ic:Z.msg,s:"chat:"+c.id},{l:"Inviter",ic:Z.plus,s:"invite"},{l:"Calendrier",ic:Z.cal,s:"calendar"}].map((a,i)=><button key={i} onClick={()=>go(a.s)} style={{flex:"1 1 22%",display:"flex",flexDirection:"column",alignItems:"center",gap:4,background:C.card,border:`1px solid ${C.brd}`,borderRadius:12,padding:"10px 0",cursor:"pointer",fontSize:11,fontWeight:600,color:C.blue}}>{a.ic}<span>{a.l}</span></button>)}</div>
<div style={{display:"flex",gap:6,marginBottom:16}}>{[{l:"Stats",ic:Z.tgt,s:"circleStats"},...(c.admin?[{l:"Rappel",ic:Z.bell,s:"remind"},{l:"Modifier",ic:Z.gear,s:"editCircle"}]:[]),{l:"Quitter",ic:Z.warn,s:"leaveCircle",c:C.red}].map((a,i)=><button key={i} onClick={()=>go(a.s)} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:4,background:C.card,border:`1px solid ${a.c?a.c+"20":C.brd}`,borderRadius:12,padding:"10px 0",cursor:"pointer",fontSize:10,fontWeight:600,color:a.c||C.t2}}>{a.ic}<span>{a.l}</span></button>)}</div>
{!c.admin&&<div style={{background:C.blueL,borderRadius:10,padding:"8px 14px",marginBottom:12,fontSize:12,color:C.t2}}>Admin: <span style={{fontWeight:700,color:C.t1}}>Grace M.</span></div>}
{/* Tabs */}
<div style={{display:"flex",background:C.card,borderRadius:50,padding:3,marginBottom:16,border:`1px solid ${C.brd}`}}>{[{k:"m",l:"Membres"},{k:"r",l:"Rotation"},{k:"g",l:"Règles"}].map(t=><button key={t.k} onClick={()=>setTab(t.k)} style={{flex:1,padding:"10px 0",borderRadius:50,border:"none",background:tab===t.k?C.blue:"transparent",color:tab===t.k?"#fff":C.t3,fontSize:12,fontWeight:600,cursor:"pointer"}}>{t.l}</button>)}</div>
{tab==="m"&&<div><div style={{fontSize:12,color:C.t3,marginBottom:10}}><span style={{color:C.green,fontWeight:700}}>{paid}</span> payé(s) · <span style={{color:C.red,fontWeight:700}}>{MEM.length-paid}</span> en attente</div>{MEM.map(m=><div key={m.id} onClick={()=>go("mem:"+m.id)} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 16px",background:C.card,borderRadius:16,marginBottom:6,border:`1px solid ${C.brdL}`,cursor:"pointer"}}><Av ini={m.i} sz={40}/><div style={{flex:1}}><div style={{display:"flex",alignItems:"center",gap:6}}><span style={{fontSize:14,fontWeight:600,color:C.t1}}>{m.n}</span>{((c.admin&&m.id===1)||(!c.admin&&m.id===2))&&<span style={{fontSize:9,fontWeight:700,color:C.blue,background:C.blueL,padding:"2px 6px",borderRadius:4}}>ADMIN</span>}</div><div style={{fontSize:12,color:C.t3}}>{m.p}{m.pen>0&&<span style={{color:C.red}}> · Pénalité: {fm(m.pen)} F</span>}</div></div><div style={{textAlign:"center",marginRight:8}}><div style={{fontSize:9,color:C.t3,fontWeight:600}}>TOUR</div><div style={{fontSize:16,fontWeight:800,color:C.gold}}>{m.t}</div></div><Bdg s={m.ok?"paid":"pending"}/></div>)}</div>}
{tab==="r"&&MEM.map((m,i)=><div key={m.id} style={{display:"flex",alignItems:"center",gap:12,padding:"14px 16px",background:i===0?C.blueL:C.card,borderRadius:16,marginBottom:6,border:`1.5px solid ${i===0?C.blue+"40":C.brdL}`}}><div style={{width:30,height:30,borderRadius:8,background:i===0?C.blue:C.bg,display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:800,color:i===0?"#fff":C.t3}}>{m.t}</div><Av ini={m.i} sz={36}/><div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,color:C.t1}}>{m.n}</div></div><span style={{fontSize:14,fontWeight:700,color:i===0?C.gold:C.t4}}>{fm(c.tot)} F</span></div>)}
{tab==="g"&&[{l:"Montant/tour",v:fm(c.amt)+" FCFA"},{l:"Fréquence",v:c.freq},{l:"Membres",v:c.mem},{l:"Pénalité",v:c.pen+"%"},{l:"Paiement",v:"Kolo Pay / Mobile Money"},{l:"Code",v:c.code}].map((r,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"13px 16px",background:C.card,borderRadius:12,marginBottom:6,border:`1px solid ${C.brdL}`}}><span style={{fontSize:13,color:C.t3}}>{r.l}</span><span style={{fontSize:13,fontWeight:700,color:C.t1}}>{r.v}</span></div>)}
</Scroll>;}

function Chat({go,cid}){const c=CIR.find(x=>x.id===cid)||CIR[0];const[msg,setMsg]=useState("");const[msgs,setMsgs]=useState(MSGS);const ref=useRef(null);
const doSend=()=>{if(!msg.trim())return;setMsgs(p=>[...p,{id:Date.now(),from:"Joeldy T.",ini:"JT",msg:msg.trim(),time:new Date().toLocaleTimeString("fr",{hour:"2-digit",minute:"2-digit"}),me:true}]);setMsg("");setTimeout(()=>{if(ref.current)ref.current.scrollTop=ref.current.scrollHeight;},50);};
return <div style={{height:"100%",display:"flex",flexDirection:"column",background:C.bg}}>
<div style={{padding:"12px 18px"}}><Hdr title={c.name} onBack={()=>go("back")} right={<span style={{fontSize:12,color:C.t3}}>{c.mem} membres</span>}/></div>
<div ref={ref} style={{flex:1,overflowY:"auto",padding:"0 18px 12px"}}>{msgs.map(m=><div key={m.id} style={{display:"flex",justifyContent:m.me?"flex-end":"flex-start",marginBottom:10}}>{!m.me&&<Av ini={m.ini} sz={28}/>}<div style={{marginLeft:m.me?0:8,maxWidth:"75%"}}>{!m.me&&<div style={{fontSize:11,fontWeight:600,color:C.blue,marginBottom:2}}>{m.from}</div>}<div style={{padding:"10px 14px",borderRadius:16,borderTopLeftRadius:m.me?16:4,borderTopRightRadius:m.me?4:16,background:m.me?C.blue:C.card,color:m.me?"#fff":C.t1,fontSize:13,lineHeight:1.4,boxShadow:m.me?"none":C.sh}}>{m.msg}</div><div style={{fontSize:10,color:C.t4,marginTop:2,textAlign:m.me?"right":"left"}}>{m.time}</div></div></div>)}</div>
<div style={{padding:"8px 18px 16px",background:C.card,borderTop:`1px solid ${C.brd}`}}><div style={{display:"flex",gap:8}}><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==="Enter"&&doSend()} placeholder="Message..." style={{flex:1,padding:"12px 16px",borderRadius:50,border:`1px solid ${C.brd}`,background:C.bg,outline:"none",fontSize:14,color:C.t0}}/><button onClick={doSend} style={{width:44,height:44,borderRadius:22,background:`linear-gradient(135deg,${C.blue},${C.blueD})`,border:"none",cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",flexShrink:0}}>{Z.send}</button></div></div></div>;}

// ── Contribute/Confirm ──
function Contribute({go}){const[sel,setSel]=useState(1);const[wal,setWal]=useState(0);
return <Scroll><Hdr title="Cotiser" onBack={()=>go("back")}/>
{CIR.map(c=><button key={c.id} onClick={()=>setSel(c.id)} style={{display:"flex",alignItems:"center",gap:12,padding:"14px 16px",width:"100%",background:sel===c.id?C.blueL:C.card,borderRadius:16,marginBottom:6,cursor:"pointer",border:`1.5px solid ${sel===c.id?C.blue:C.brdL}`,textAlign:"left"}}><div style={{width:40,height:40,borderRadius:12,background:C.blueL,display:"flex",alignItems:"center",justifyContent:"center",color:C.blue}}>{Z.grp}</div><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600,color:C.t1}}>{c.name}</div><div style={{fontSize:12,color:C.t3}}>{fm(c.amt)} FCFA / {c.freq.toLowerCase()}</div></div>{sel===c.id&&Z.ok}</button>)}
<div style={{fontSize:13,fontWeight:600,color:C.t2,marginTop:16,marginBottom:10}}>Payer via</div>
{WALLETS.map((w,i)=><button key={w.id} onClick={()=>setWal(i)} style={{display:"flex",alignItems:"center",gap:12,padding:"14px 16px",width:"100%",background:wal===i?C.blueL:C.card,borderRadius:16,marginBottom:6,border:`1.5px solid ${wal===i?C.blue:C.brdL}`,cursor:"pointer",textAlign:"left"}}><SvgIc type={w.logo} size={24}/><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600,color:C.t1}}>{w.n}</div><div style={{fontSize:12,color:C.t3}}>{fm(w.bal)} F</div></div>{wal===i&&<div style={{width:20,height:20,borderRadius:10,background:C.blue,display:"flex",alignItems:"center",justifyContent:"center"}}>{Z.okW}</div>}</button>)}
<div style={{marginTop:16}}><Btn full onClick={()=>go("ok")}>Cotiser</Btn></div></Scroll>;}

// ── Wallets ──
function Wallets({go}){const tot=WALLETS.reduce((s,a)=>s+a.bal,0);return <Scroll><Hdr title="Portefeuilles" onBack={()=>go("back")}/>
<div style={{background:C.card,borderRadius:16,padding:"14px 18px",display:"flex",justifyContent:"space-between",marginBottom:12,border:`1px solid ${C.brd}`}}><span style={{fontSize:13,color:C.t3}}>Solde total</span><span style={{fontSize:16,fontWeight:800,color:C.gold}}>{fm(tot)} FCFA</span></div>
<div style={{display:"flex",gap:8,marginBottom:16}}><Btn full onClick={()=>go("topup")} sx={{flex:1}}>{Z.dn} Recharger</Btn><Btn v="s" full onClick={()=>go("withdraw")} sx={{flex:1}}>{Z.up} Retirer</Btn></div>
{WALLETS.map(w=><div key={w.id} style={{background:C.card,borderRadius:16,padding:18,marginBottom:10,border:`1px solid ${C.brd}`}}>
<div style={{display:"flex",alignItems:"center",gap:12,marginBottom:10}}><SvgIc type={w.logo} size={28}/><div style={{flex:1}}><div style={{fontSize:15,fontWeight:700,color:C.t1}}>{w.n}</div><div style={{fontSize:12,color:C.t3}}>{w.num}</div></div>{w.id===0&&<span style={{fontSize:10,fontWeight:700,color:C.kolo,background:C.koloL,padding:"3px 8px",borderRadius:6}}>INTERNE</span>}</div>
<div style={{fontSize:22,fontWeight:800,color:C.gold}}>{fm(w.bal)} <span style={{fontSize:13,color:C.t3}}>FCFA</span></div></div>)}
</Scroll>;}

// ── Transfer P2P ──
function Transfer({go}){const[amt,setAmt]=useState("");const contacts=[{n:"Grace M.",p:"+242 05 512 8834",i:"GM"},{n:"Patrick K.",p:"+242 06 891 2245",i:"PK"},{n:"Merveille N.",p:"+242 05 334 7712",i:"MN"}];
return <Scroll><Hdr title="Envoyer" onBack={()=>go("back")}/>
<div style={{background:C.card,borderRadius:20,padding:"24px 20px",textAlign:"center",marginBottom:16,border:`1px solid ${C.brd}`}}><div style={{fontSize:13,color:C.t3,marginBottom:8}}>Montant</div><div style={{display:"flex",alignItems:"center",justifyContent:"center"}}><input value={amt} onChange={e=>setAmt(e.target.value)} placeholder="0" style={{fontSize:36,fontWeight:800,color:C.gold,border:"none",background:"none",outline:"none",width:160,textAlign:"center"}}/><span style={{fontSize:16,fontWeight:600,color:C.t3}}>FCFA</span></div></div>
<div style={{display:"flex",gap:8,marginBottom:16}}>{[5000,10000,25000,50000].map(v=><button key={v} onClick={()=>setAmt(String(v))} style={{flex:1,padding:"10px 0",borderRadius:10,border:`1px solid ${amt===String(v)?C.blue:C.brd}`,background:amt===String(v)?C.blueL:C.card,color:amt===String(v)?C.blue:C.t2,fontSize:12,fontWeight:600,cursor:"pointer"}}>{fm(v)}</button>)}</div>
<div style={{fontSize:13,fontWeight:600,color:C.t2,marginBottom:10}}>Contacts</div>
{contacts.map((c,i)=><button key={i} onClick={()=>go("ok")} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 16px",width:"100%",background:C.card,borderRadius:14,marginBottom:6,border:`1px solid ${C.brdL}`,cursor:"pointer",textAlign:"left"}}><Av ini={c.i} sz={40}/><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600,color:C.t1}}>{c.n}</div><div style={{fontSize:12,color:C.t3}}>{c.p}</div></div><span style={{color:C.t4}}>{Z.fwd}</span></button>)}
</Scroll>;}

// ── Request Money ──
function RequestMoney({go}){const[amt,setAmt]=useState("");
return <Scroll><Hdr title="Demander de l'argent" onBack={()=>go("back")}/>
<div style={{background:C.card,borderRadius:20,padding:"24px 20px",textAlign:"center",marginBottom:16,border:`1px solid ${C.brd}`}}><div style={{fontSize:13,color:C.t3,marginBottom:8}}>Montant</div><div style={{display:"flex",alignItems:"center",justifyContent:"center"}}><input value={amt} onChange={e=>setAmt(e.target.value)} placeholder="0" style={{fontSize:36,fontWeight:800,color:C.blue,border:"none",background:"none",outline:"none",width:160,textAlign:"center"}}/><span style={{fontSize:16,fontWeight:600,color:C.t3}}>FCFA</span></div></div>
<Inp label="Motif" ph="Ex: Remboursement cotisation"/>
<div style={{marginTop:12}}><Btn full onClick={()=>go("ok")} dis={!amt}>Envoyer la demande</Btn></div></Scroll>;}

// ── Bills ──
function Bills({go}){const[sel,setSel]=useState(null);const[num,setNum]=useState("");const[amt,setAmt]=useState("");
const bills=[{n:"Électricité (SNE)",col:C.gold},{n:"Eau (SNDE)",col:C.blue},{n:"Canal+",col:C.navy},{n:"Startimes",col:C.orange},{n:"Internet",col:C.green},{n:"DSTV",col:C.purple}];
return <Scroll><Hdr title="Factures" onBack={()=>go("back")}/>
{sel===null?<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{bills.map((b,i)=><button key={i} onClick={()=>setSel(i)} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:8,padding:"20px 10px",background:C.card,borderRadius:16,border:`1px solid ${C.brd}`,cursor:"pointer"}}><div style={{width:44,height:44,borderRadius:14,background:b.col+"15",display:"flex",alignItems:"center",justifyContent:"center",color:b.col,fontSize:14,fontWeight:800}}>{b.n[0]}</div><span style={{fontSize:13,fontWeight:600,color:C.t1}}>{b.n}</span></button>)}</div>
:<div><button onClick={()=>setSel(null)} style={{background:C.blueL,borderRadius:12,padding:"10px 16px",border:"none",cursor:"pointer",marginBottom:16,color:C.blue,fontWeight:600,fontSize:13}}>{bills[sel].n}</button><Inp label="N° abonné" ph="12345678" val={num} set={setNum}/><Inp label="Montant" ph="15000" val={amt} set={setAmt} type="number"/><Btn full onClick={()=>go("ok")} dis={!num||!amt}>Payer {amt?fm(amt)+" F":""}</Btn></div>}
</Scroll>;}

// ── Notifications ──
function Notif({go}){const im={warn:{bg:C.orangeL,c:C.orange},"in":{bg:C.greenL,c:C.green},gift:{bg:C.purpleL,c:C.purple},add:{bg:C.blueL,c:C.blue},pen:{bg:C.redL,c:C.red}};
return <Scroll><Hdr title="Notifications" onBack={()=>go("back")}/>{NOTIFS.map(n=>{const ic=im[n.tp]||im.warn;return <div key={n.id} style={{display:"flex",gap:12,padding:"14px 16px",background:C.card,borderRadius:16,marginBottom:8,border:`1px solid ${n.rd?C.brdL:C.blue+"20"}`,opacity:n.rd?.6:1}}><div style={{width:42,height:42,borderRadius:12,background:ic.bg,display:"flex",alignItems:"center",justifyContent:"center",color:ic.c,flexShrink:0}}>{Z.bell}</div><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600,color:C.t1}}>{n.tt}</div><div style={{fontSize:12,color:C.t3,marginTop:2}}>{n.ds}</div><div style={{fontSize:11,color:C.t4,marginTop:4}}>{n.tm}</div></div></div>;})}</Scroll>;}

// ── Profile/Security/Settings ──
function EditProfile({go}){return <Scroll><Hdr title="Modifier le profil" onBack={()=>go("back")}/><div style={{textAlign:"center",marginBottom:24}}><Av ini="JT" sz={80} col={C.blue}/></div><Inp label="Nom" ph="Joeldy Tsina" val="Joeldy Tsina" set={()=>{}}/><Inp label="Téléphone" ph="+242 06 466 3469" val="+242 06 466 3469" set={()=>{}}/><Inp label="Email" ph="joeldytsina94@gmail.com" val="joeldytsina94@gmail.com" set={()=>{}}/><Btn full onClick={()=>go("back")}>Enregistrer</Btn></Scroll>;}
function Sec({go}){return <Scroll><Hdr title="Sécurité" onBack={()=>go("back")}/><MenuRow icon={Z.lock} label="Changer le PIN" onClick={()=>go("ok")}/><MenuRow icon={Z.lock} label="Changer le mot de passe" onClick={()=>go("ok")}/><MenuRow icon={Z.shield} label="2FA" right={<span style={{fontSize:12,fontWeight:700,color:C.green}}>Activé</span>}/><MenuRow icon={Z.phone} label="Biométrie" right={<span style={{fontSize:12,fontWeight:700,color:C.green}}>Activé</span>}/></Scroll>;}
function Settings({go}){const[n,sN]=useState(true);const[b,sB]=useState(true);return <Scroll><Hdr title="Paramètres" onBack={()=>go("back")}/>{[{l:"Notifications push",v:n,s:sN},{l:"Biométrie",v:b,s:sB}].map((t,i)=><div key={i} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"16px 18px",background:C.card,borderRadius:16,marginBottom:8,border:`1px solid ${C.brdL}`}}><span style={{fontSize:14,color:C.t1}}>{t.l}</span><Toggle v={t.v} set={t.s}/></div>)}<MenuRow icon={Z.shield} label="Sécurité" onClick={()=>go("sec")}/><MenuRow icon={Z.globe} label="Langue" onClick={()=>go("lang")}/><MenuRow icon={Z.help} label="FAQ" onClick={()=>go("faq")}/><div style={{marginTop:20}}><button onClick={()=>go("login")} style={{width:"100%",padding:"14px",borderRadius:50,border:`1.5px solid ${C.red}`,background:"none",color:C.red,fontSize:14,fontWeight:600,cursor:"pointer"}}>Se déconnecter</button></div></Scroll>;}
function Lang({go}){return <Scroll><Hdr title="Langue" onBack={()=>go("back")}/>{[{n:"Français",f:"FR",a:true},{n:"Lingala",f:"LN",a:false},{n:"English",f:"EN",a:false}].map(l=><div key={l.f} style={{display:"flex",alignItems:"center",gap:14,padding:"16px",background:C.card,borderRadius:16,marginBottom:8,border:`1.5px solid ${l.a?C.blue:C.brdL}`,cursor:"pointer"}}><div style={{width:36,height:36,borderRadius:10,background:l.a?C.blueL:C.bg,display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,fontWeight:700,color:l.a?C.blue:C.t3}}>{l.f}</div><span style={{flex:1,fontSize:14,fontWeight:600,color:C.t1}}>{l.n}</span>{l.a&&<div style={{width:20,height:20,borderRadius:10,background:C.blue,display:"flex",alignItems:"center",justifyContent:"center"}}>{Z.okW}</div>}</div>)}</Scroll>;}
function FAQ({go}){const[o,setO]=useState(null);return <Scroll><Hdr title="FAQ" onBack={()=>go("back")}/>{FAQS.map((f,i)=><div key={i} style={{background:C.card,borderRadius:16,marginBottom:8,border:`1px solid ${C.brdL}`,overflow:"hidden"}}><button onClick={()=>setO(o===i?null:i)} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"16px",width:"100%",background:"none",border:"none",cursor:"pointer",textAlign:"left"}}><span style={{fontSize:14,fontWeight:600,color:C.t1,flex:1}}>{f.q}</span><span style={{color:C.t3,transform:o===i?"rotate(90deg)":"none",transition:"0.2s"}}>{Z.fwd}</span></button>{o===i&&<div style={{padding:"0 16px 16px",fontSize:13,color:C.t2,lineHeight:1.5}}>{f.a}</div>}</div>)}</Scroll>;}

// ── Create/Join/Invite/QR/Remind/Savings/Receipts ──
function CreateCircle({go}){const[name,setName]=useState("");const[amt,setAmt]=useState("");return <Scroll><Hdr title="Créer un cercle" onBack={()=>go("back")}/><Inp label="Nom" ph="Ex: Cercle Famille" val={name} set={setName}/><Inp label="Montant/tour (FCFA)" ph="25000" val={amt} set={setAmt} type="number"/><div style={{marginBottom:16}}><label style={{fontSize:13,fontWeight:600,color:C.t2,marginBottom:6,display:"block"}}>Fréquence</label><div style={{display:"flex",gap:8}}>{["Hebdo","Bi-mensuel","Mensuel"].map(f=><button key={f} style={{flex:1,padding:"12px 0",borderRadius:12,border:"none",cursor:"pointer",background:f==="Mensuel"?C.blue:C.card,color:f==="Mensuel"?"#fff":C.t2,fontSize:13,fontWeight:600}}>{f}</button>)}</div></div><Btn full onClick={()=>go("ok")} dis={!name||!amt}>Créer</Btn></Scroll>;}
function JoinCircle({go}){const[code,setCode]=useState("");return <Scroll><Hdr title="Rejoindre" onBack={()=>go("back")}/><div style={{textAlign:"center",marginBottom:32}}><div style={{width:60,height:60,borderRadius:20,background:C.blueL,display:"inline-flex",alignItems:"center",justifyContent:"center",marginBottom:16,color:C.blue}}>{Z.link}</div><h3 style={{fontSize:18,fontWeight:700,color:C.t0}}>Code d'invitation</h3></div><Inp label="Code" ph="ELITE2026" val={code} set={setCode}/><Btn full onClick={()=>go("ok")} dis={!code}>Rejoindre</Btn></Scroll>;}
function Invite({go}){return <Scroll><Hdr title="Inviter" onBack={()=>go("back")}/><div style={{background:C.card,borderRadius:16,padding:20,border:`1px solid ${C.brd}`,textAlign:"center",marginBottom:20}}><div style={{fontSize:24,fontWeight:800,color:C.blue,letterSpacing:2,marginBottom:12}}>ELITE2026</div><Btn v="s" full>{Z.copy} Copier</Btn></div>{["WhatsApp","SMS","Lien"].map((m,i)=><button key={i} style={{display:"flex",alignItems:"center",gap:14,padding:"14px 16px",width:"100%",background:C.card,borderRadius:12,marginBottom:8,border:`1px solid ${C.brdL}`,cursor:"pointer"}}><div style={{width:36,height:36,borderRadius:10,background:C.blueL,display:"flex",alignItems:"center",justifyContent:"center",color:C.blue,fontWeight:700,fontSize:14}}>{m[0]}</div><span style={{flex:1,fontSize:14,color:C.t1}}>Inviter via {m}</span><span style={{color:C.t4}}>{Z.fwd}</span></button>)}</Scroll>;}
function QR({go}){const[tab,setTab]=useState("my");return <Scroll><Hdr title="QR Code" onBack={()=>go("back")}/>
<div style={{display:"flex",background:C.card,borderRadius:50,padding:3,marginBottom:20,border:`1px solid ${C.brd}`}}>{[{k:"my",l:"Mon QR"},{k:"scan",l:"Scanner"}].map(t=><button key={t.k} onClick={()=>setTab(t.k)} style={{flex:1,padding:"10px 0",borderRadius:50,border:"none",background:tab===t.k?C.blue:"transparent",color:tab===t.k?"#fff":C.t3,fontSize:13,fontWeight:600,cursor:"pointer"}}>{t.l}</button>)}</div>
{tab==="my"?<div style={{textAlign:"center"}}>
<div style={{background:C.card,borderRadius:24,padding:32,border:`1px solid ${C.brd}`,display:"inline-block",marginBottom:20}}>
<div style={{width:200,height:200,background:C.navy,borderRadius:16,display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 16px",position:"relative",overflow:"hidden"}}>
<div style={{width:170,height:170,background:"#fff",borderRadius:12,display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr 1fr",gridTemplateRows:"1fr 1fr 1fr 1fr 1fr",gap:4,padding:12}}>
{[1,1,1,0,1, 0,0,1,0,0, 1,0,1,0,1, 0,1,0,1,0, 1,0,1,1,1].map((n,i)=><div key={i} style={{background:i===12?C.blue:n?C.navy:"transparent",borderRadius:i===12?4:2}}/>)}
</div>
</div>
<div style={{fontSize:18,fontWeight:700,color:C.t0}}>Joeldy Tsina</div>
<div style={{fontSize:13,color:C.t3,marginTop:4}}>+242 06 466 3469</div>
<div style={{fontSize:12,color:C.kolo,fontWeight:600,marginTop:8,background:C.koloL,padding:"4px 12px",borderRadius:20,display:"inline-block"}}>Kolo Pay</div>
</div>
<div style={{display:"flex",gap:8}}>
<Btn v="s" full sx={{flex:1}}>{Z.copy} Copier</Btn>
<Btn full sx={{flex:1}}>{Z.send} Partager</Btn>
</div>
<div style={{marginTop:16,fontSize:12,color:C.t3}}>Scannez ce QR pour recevoir un paiement via Kolo Pay, MTN ou Airtel Money</div>
</div>
:<div>
<div style={{width:"100%",height:300,background:C.card,borderRadius:24,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",border:`2px dashed ${C.blue}`,marginBottom:20,position:"relative",overflow:"hidden"}}>
<div style={{position:"absolute",inset:40,border:`3px solid ${C.blue}`,borderRadius:16,opacity:.3}}/>
<div style={{position:"absolute",top:40,left:40,width:24,height:24,borderTop:`4px solid ${C.blue}`,borderLeft:`4px solid ${C.blue}`,borderRadius:"4px 0 0 0"}}/>
<div style={{position:"absolute",top:40,right:40,width:24,height:24,borderTop:`4px solid ${C.blue}`,borderRight:`4px solid ${C.blue}`,borderRadius:"0 4px 0 0"}}/>
<div style={{position:"absolute",bottom:40,left:40,width:24,height:24,borderBottom:`4px solid ${C.blue}`,borderLeft:`4px solid ${C.blue}`,borderRadius:"0 0 0 4px"}}/>
<div style={{position:"absolute",bottom:40,right:40,width:24,height:24,borderBottom:`4px solid ${C.blue}`,borderRight:`4px solid ${C.blue}`,borderRadius:"0 0 4px 0"}}/>
<div style={{color:C.blue,marginBottom:12}}>{Z.cam}</div>
<div style={{fontSize:14,fontWeight:600,color:C.t1}}>Pointez la caméra</div>
<div style={{fontSize:12,color:C.t3,marginTop:4}}>vers un QR Likelemba</div>
</div>
<Btn v="s" full onClick={()=>setTab("my")}>Afficher mon QR</Btn>
</div>}
</Scroll>;}
function Remind({go}){const up=MEM.filter(m=>!m.ok);return <Scroll><Hdr title="Rappel" onBack={()=>go("back")}/><div style={{background:C.orangeL,borderRadius:16,padding:"14px 18px",marginBottom:18,border:`1px solid ${C.orange}20`}}><div style={{fontSize:13,fontWeight:700,color:C.orange}}>{up.length} en attente</div></div>{MEM.map(m=><div key={m.id} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 16px",background:C.card,borderRadius:16,marginBottom:6,border:`1px solid ${C.brdL}`,opacity:m.ok?.5:1}}><Av ini={m.i} sz={40}/><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600,color:C.t1}}>{m.n}</div></div><Bdg s={m.ok?"paid":"pending"}/></div>)}<div style={{marginTop:16}}><Btn full onClick={()=>go("ok")}>Envoyer le rappel</Btn></div></Scroll>;}
function Sav({go}){return <Scroll><Hdr title="Objectifs d'épargne" onBack={()=>go("back")}/>{SAV.map(s=><div key={s.id} style={{background:C.card,borderRadius:16,padding:"16px 18px",marginBottom:10,border:`1px solid ${C.brdL}`}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><span style={{fontSize:14,fontWeight:600,color:C.t1}}>{s.n}</span><span style={{fontSize:13,fontWeight:700,color:s.sv>=s.tg?C.green:C.gold}}>{fm(s.sv)}/{fm(s.tg)}</span></div><div style={{background:C.bg,borderRadius:4,height:6,overflow:"hidden"}}><div style={{width:`${Math.min(s.sv/s.tg*100,100)}%`,height:"100%",background:s.cl,borderRadius:4}}/></div></div>)}</Scroll>;}
function Rcpt({go}){return <Scroll><Hdr title="Reçus" onBack={()=>go("back")}/>{RCPT.map(r=><div key={r.id} style={{display:"flex",alignItems:"center",gap:12,padding:16,background:C.card,borderRadius:16,marginBottom:8,border:`1px solid ${C.brdL}`}}><div style={{width:42,height:42,borderRadius:12,background:C.blueL,display:"flex",alignItems:"center",justifyContent:"center",color:C.blue}}>{Z.doc}</div><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600,color:C.t1}}>{r.c}</div><div style={{fontSize:12,color:C.t3}}>{r.r} · {r.d}</div></div><div style={{textAlign:"right"}}><div style={{fontSize:14,fontWeight:700,color:C.gold}}>{fm(r.a)} F</div><Bdg s={r.s}/></div></div>)}</Scroll>;}
function Withdraw({go}){const[amt,setAmt]=useState("");return <Scroll><Hdr title="Retrait Kolo Pay" onBack={()=>go("back")}/><div style={{background:C.card,borderRadius:20,padding:20,textAlign:"center",marginBottom:16,border:`1px solid ${C.brd}`}}><div style={{fontSize:13,color:C.t3}}>Solde</div><div style={{fontSize:28,fontWeight:800,color:C.gold}}>{fm(95000)} F</div></div><Inp label="Montant" ph="0" val={amt} set={setAmt} type="number"/><div style={{fontSize:12,color:C.t3,marginBottom:16}}>Vers MTN ou Airtel Money · Frais 1%</div><Btn full onClick={()=>go("ok")} dis={!amt}>Retirer</Btn></Scroll>;}
function TopUp({go}){const[amt,setAmt]=useState("");return <Scroll><Hdr title="Recharger Kolo Pay" onBack={()=>go("back")}/><div style={{display:"flex",gap:8,marginBottom:16}}>{[5000,10000,25000,50000].map(v=><button key={v} onClick={()=>setAmt(String(v))} style={{flex:1,padding:"10px 0",borderRadius:10,border:`1px solid ${amt===String(v)?C.blue:C.brd}`,background:amt===String(v)?C.blueL:C.card,color:amt===String(v)?C.blue:C.t2,fontSize:12,fontWeight:600,cursor:"pointer"}}>{fm(v)}</button>)}</div><Inp label="Ou saisir un montant" ph="0" val={amt} set={setAmt} type="number"/><div style={{fontSize:12,color:C.t3,marginBottom:16}}>Depuis MTN ou Airtel Money</div><Btn full onClick={()=>go("ok")} dis={!amt}>Recharger {amt?fm(amt)+" F":""}</Btn></Scroll>;}
function MemberProf({go,mid}){const m=MEM.find(x=>x.id===mid)||MEM[0];return <Scroll><Hdr title="Profil membre" onBack={()=>go("back")}/><div style={{background:C.card,borderRadius:20,padding:24,textAlign:"center",border:`1px solid ${C.brd}`,marginBottom:16}}><Av ini={m.i} sz={64} col={C.blue}/><div style={{fontSize:18,fontWeight:700,color:C.t0,marginTop:10}}>{m.n}</div><div style={{fontSize:13,color:C.t3}}>{m.p}</div><div style={{display:"flex",gap:12,justifyContent:"center",marginTop:14}}>{[{l:"Tour",v:m.t,c:C.gold},{l:"Statut",v:m.ok?"Payé":"En attente",c:m.ok?C.green:C.orange}].map((s,i)=><div key={i} style={{padding:"8px 14px",background:C.bg,borderRadius:10}}><div style={{fontSize:14,fontWeight:800,color:s.c}}>{s.v}</div><div style={{fontSize:10,color:C.t3}}>{s.l}</div></div>)}</div></div></Scroll>;}
function LeaveCircle({go}){const[ok,setOk]=useState(false);return <Scroll><Hdr title="Quitter le cercle" onBack={()=>go("back")}/><div style={{textAlign:"center",marginBottom:24}}><div style={{width:64,height:64,borderRadius:20,background:C.redL,display:"inline-flex",alignItems:"center",justifyContent:"center",marginBottom:16,color:C.red}}>{Z.warn}</div><h3 style={{fontSize:20,fontWeight:800,color:C.t0}}>Êtes-vous sûr ?</h3></div><div style={{background:C.redL,borderRadius:16,padding:16,marginBottom:20,border:`1px solid ${C.red}20`}}>{["Vous perdrez votre position","Cotisations non remboursées","30 jours avant de rejoindre à nouveau"].map((t,i)=><div key={i} style={{fontSize:12,color:C.t2,marginBottom:6,paddingLeft:12,borderLeft:`2px solid ${C.red}40`}}>{t}</div>)}</div><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:24}}><button onClick={()=>setOk(!ok)} style={{width:22,height:22,borderRadius:6,border:`2px solid ${ok?C.red:C.brd}`,background:ok?C.red:"transparent",cursor:"pointer",flexShrink:0,display:"flex",alignItems:"center",justifyContent:"center"}}>{ok&&Z.okW}</button><span style={{fontSize:13,color:C.t2}}>Je comprends</span></div><Btn full onClick={()=>go("ok")} dis={!ok} sx={{background:ok?C.red:"#ccc",boxShadow:"none"}}>Quitter</Btn></Scroll>;}
function EditCircle({go}){return <Scroll><Hdr title="Modifier" onBack={()=>go("back")}/><Inp label="Nom" ph="Cercle Élite" val="Cercle Élite" set={()=>{}}/><Inp label="Montant" ph="25000" val="25000" set={()=>{}}/><Inp label="Pénalité (%)" ph="5" val="5" set={()=>{}}/><div style={{fontSize:14,fontWeight:600,color:C.t1,marginBottom:10}}>Membres</div>{MEM.map(m=><div key={m.id} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 16px",background:C.card,borderRadius:14,marginBottom:6,border:`1px solid ${C.brdL}`}}><Av ini={m.i} sz={36}/><div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,color:C.t1}}>{m.n}</div></div>{m.id!==1&&<button style={{fontSize:11,fontWeight:600,color:C.red,background:C.redL,border:"none",borderRadius:8,padding:"4px 10px",cursor:"pointer"}}>Exclure</button>}{m.id===1&&<span style={{fontSize:11,fontWeight:700,color:C.blue,background:C.blueL,padding:"4px 10px",borderRadius:8}}>Admin</span>}</div>)}<Btn full onClick={()=>go("ok")}>Enregistrer</Btn></Scroll>;}
function Calendar({go}){const ms=["Jan","Fév","Mar","Avr","Mai","Jun"];return <Scroll><Hdr title="Calendrier" onBack={()=>go("back")}/>{ms.map((m,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:12,padding:"14px 16px",background:C.card,borderRadius:16,marginBottom:8,border:`1.5px solid ${i===3?C.blue+"50":C.brdL}`,opacity:i<3?.6:1}}><div style={{width:44,height:44,borderRadius:14,background:i===3?C.blueL:i<3?C.greenL:C.bg,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:10,fontWeight:700,color:i===3?C.blue:i<3?C.green:C.t3}}>{m}</span><span style={{fontSize:14,fontWeight:800,color:i===3?C.blue:i<3?C.green:C.t1}}>01</span></div><div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,color:C.t1}}>Tour de {MEM[i%MEM.length].n}</div><div style={{fontSize:12,color:C.t3}}>{fm(25000)} FCFA</div></div>{i<3&&<Bdg s="paid"/>}{i===3&&<Bdg s="pending"/>}</div>)}</Scroll>;}
function CircleStats({go}){const data=[{l:"Jan",v:100},{l:"Fév",v:95},{l:"Mar",v:88},{l:"Avr",v:67}];return <Scroll><Hdr title="Statistiques" onBack={()=>go("back")}/><div style={{display:"flex",gap:10,marginBottom:16}}>{[{l:"Ponctualité",v:"87%",c:C.green,bg:C.greenL},{l:"Collecté",v:"402K",c:C.gold,bg:C.goldL},{l:"Pénalités",v:"2.5K",c:C.red,bg:C.redL}].map((s,i)=><div key={i} style={{flex:1,textAlign:"center",padding:"14px 8px",background:s.bg,borderRadius:14}}><div style={{fontSize:18,fontWeight:800,color:s.c}}>{s.v}</div><div style={{fontSize:10,color:C.t3}}>{s.l}</div></div>)}</div><div style={{background:C.card,borderRadius:20,padding:20,border:`1px solid ${C.brd}`}}><div style={{fontSize:14,fontWeight:700,color:C.t1,marginBottom:16}}>Collecte mensuelle (%)</div><div style={{display:"flex",alignItems:"flex-end",gap:8,height:120}}>{data.map((d,i)=><div key={i} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",gap:4}}><span style={{fontSize:10,fontWeight:600,color:C.blue}}>{d.v}%</span><div style={{width:"100%",borderRadius:6,height:`${d.v}%`,background:`linear-gradient(180deg,${C.blue},${C.blueD})`}}/><span style={{fontSize:10,color:C.t3}}>{d.l}</span></div>)}</div></div></Scroll>;}

export { CircleDetail, Chat, Contribute, CreateCircle, JoinCircle, Invite, QR, Remind, EditCircle, Calendar, CircleStats, LeaveCircle, MemberProf };
