import { useState } from "react";
import { C, fm } from "../theme";
import { Z } from "../icons";
import { Btn, Hdr, Scroll } from "../components";

function Marketplace({go}){const pubs=[{id:10,name:"Cercle 50K",amt:50000,dur:"6 mois",mem:6,filled:4,minFee:0},{id:11,name:"Cercle 100K",amt:100000,dur:"10 mois",mem:10,filled:7,minFee:2},{id:12,name:"Cercle 25K",amt:25000,dur:"6 mois",mem:6,filled:2,minFee:0}];
return <Scroll><Hdr title="Cercles publics" onBack={()=>go("back")}/>
<div style={{background:`linear-gradient(135deg,${C.blue},${C.blueD})`,borderRadius:16,padding:"16px 18px",marginBottom:16}}><div style={{fontSize:14,fontWeight:700,color:"#fff"}}>25% de réduction !</div><div style={{fontSize:11,color:"rgba(255,255,255,0.7)"}}>Sur vos 2 premiers versements</div></div>
{pubs.map(c=><div key={c.id} style={{background:C.card,borderRadius:20,padding:18,marginBottom:12,border:`1px solid ${C.brd}`}}>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><div><div style={{fontSize:16,fontWeight:700,color:C.t0}}>{c.name}</div><div style={{fontSize:12,color:C.t3}}>{c.dur} · {c.mem} membres</div></div><div style={{textAlign:"right"}}><div style={{fontSize:18,fontWeight:800,color:C.gold}}>{fm(c.amt)} F</div></div></div>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><span style={{fontSize:11,color:C.t3}}>{c.filled}/{c.mem} places</span><span style={{fontSize:11,fontWeight:600,color:c.mem-c.filled<=2?C.red:C.green}}>{c.mem-c.filled} dispo</span></div>
<div style={{background:C.bg,borderRadius:4,height:6,overflow:"hidden",marginBottom:12}}><div style={{width:`${(c.filled/c.mem)*100}%`,height:"100%",background:`linear-gradient(90deg,${C.blue},${C.gold})`}}/></div>
<Btn full onClick={()=>go("kyc")} sx={{padding:"10px 20px",fontSize:13}}>Rejoindre · dès {c.minFee}%</Btn></div>)}
</Scroll>;}
function KYC({go}){const[step,setStep]=useState(1);return <Scroll><Hdr title="Vérification KYC" onBack={()=>go("back")}/><div style={{display:"flex",gap:4,marginBottom:24}}>{[1,2,3].map(s=><div key={s} style={{flex:1,height:4,borderRadius:2,background:s<=step?C.blue:C.brd}}/>)}</div>{step===1&&<div style={{textAlign:"center"}}><div style={{width:80,height:80,borderRadius:24,background:C.blueL,display:"inline-flex",alignItems:"center",justifyContent:"center",marginBottom:12,color:C.blue}}>{Z.doc}</div><h3 style={{fontSize:18,fontWeight:700,color:C.t0}}>Carte d'identité</h3><p style={{color:C.t3,fontSize:13,marginBottom:24}}>Photo recto de votre carte</p><div style={{background:C.card,borderRadius:20,height:180,border:`2px dashed ${C.brd}`,display:"flex",alignItems:"center",justifyContent:"center",marginBottom:16,color:C.t3}}>{Z.cam} Capturer</div><Btn full onClick={()=>setStep(2)}>Suivant</Btn></div>}{step===2&&<div style={{textAlign:"center"}}><div style={{width:80,height:80,borderRadius:24,background:C.blueL,display:"inline-flex",alignItems:"center",justifyContent:"center",marginBottom:12,color:C.blue}}>{Z.usr}</div><h3 style={{fontSize:18,fontWeight:700,color:C.t0}}>Selfie</h3><div style={{width:200,height:200,borderRadius:"50%",margin:"20px auto",border:`3px dashed ${C.blue}`,display:"flex",alignItems:"center",justifyContent:"center",color:C.blue}}>{Z.cam}</div><Btn full onClick={()=>setStep(3)}>Vérifier</Btn></div>}{step===3&&<div style={{textAlign:"center",paddingTop:40}}><div style={{width:80,height:80,borderRadius:24,background:C.greenL,display:"inline-flex",alignItems:"center",justifyContent:"center",marginBottom:16,color:C.green}}>{Z.shield}</div><h3 style={{fontSize:20,fontWeight:800,color:C.green}}>Vérifié !</h3><p style={{color:C.t3,fontSize:13,marginBottom:32}}>Vous pouvez rejoindre des cercles publics.</p><Btn full onClick={()=>go("ok")}>Continuer</Btn></div>}</Scroll>;}
function CreditScore({go}){const score=85;return <Scroll><Hdr title="Score de crédit" onBack={()=>go("back")}/><div style={{background:`linear-gradient(135deg,${C.navy},${C.navyM})`,borderRadius:24,padding:24,textAlign:"center",marginBottom:20}}><div style={{fontSize:13,color:"rgba(255,255,255,0.6)",marginBottom:8}}>Votre Score</div><div style={{position:"relative",width:120,height:120,margin:"0 auto 12px"}}><svg width="120" height="120" viewBox="0 0 120 120"><circle cx="60" cy="60" r="52" fill="none" stroke="rgba(255,255,255,0.1)" strokeWidth="8"/><circle cx="60" cy="60" r="52" fill="none" stroke={C.gold} strokeWidth="8" strokeDasharray={`${score*3.27} 327`} strokeLinecap="round" transform="rotate(-90 60 60)"/></svg><div style={{position:"absolute",top:"50%",left:"50%",transform:"translate(-50%,-50%)"}}><div style={{fontSize:32,fontWeight:800,color:C.gold}}>{score}</div><div style={{fontSize:10,color:"rgba(255,255,255,0.5)"}}>/ 100</div></div></div><div style={{fontSize:14,fontWeight:700,color:C.green}}>Excellent</div></div>{[{l:"Cotisations à temps",v:"12/12",p:100,c:C.green},{l:"Ancienneté",v:"6 mois",p:60,c:C.blue},{l:"Cercles complétés",v:"2",p:40,c:C.gold},{l:"Pénalités",v:"0",p:100,c:C.green}].map((f,i)=><div key={i} style={{background:C.card,borderRadius:14,padding:"12px 16px",marginBottom:8,border:`1px solid ${C.brdL}`}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{fontSize:13,fontWeight:600,color:C.t1}}>{f.l}</span><span style={{fontSize:13,fontWeight:700,color:f.c}}>{f.v}</span></div><div style={{background:C.bg,borderRadius:3,height:4}}><div style={{width:`${f.p}%`,height:"100%",background:f.c,borderRadius:3}}/></div></div>)}</Scroll>;}
function KoloCard({go}){const[show,setShow]=useState(false);return <Scroll><Hdr title="Kolo Card" onBack={()=>go("back")}/><div style={{background:`linear-gradient(135deg,${C.navy},#1A3A6B)`,borderRadius:20,padding:"24px 22px",marginBottom:20,boxShadow:"0 12px 40px rgba(11,29,58,0.4)"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:24}}><span style={{fontSize:12,fontWeight:700,color:"rgba(255,255,255,0.7)"}}>KOLO PAY</span><span style={{fontSize:12,fontWeight:600,color:C.gold}}>PREMIUM</span></div><div onClick={()=>setShow(!show)} style={{fontSize:18,fontWeight:600,color:"#fff",letterSpacing:3,marginBottom:20,cursor:"pointer"}}>{show?"5342 •••• •••• 8901":"•••• •••• •••• 8901"}</div><div style={{display:"flex",justifyContent:"space-between"}}><div><div style={{fontSize:9,color:"rgba(255,255,255,0.4)"}}>TITULAIRE</div><div style={{fontSize:13,fontWeight:600,color:"#fff"}}>JOELDY TSINA</div></div><div><div style={{fontSize:9,color:"rgba(255,255,255,0.4)"}}>EXPIRE</div><div style={{fontSize:13,fontWeight:600,color:"#fff"}}>12/28</div></div></div></div><div style={{display:"flex",gap:8,marginBottom:20}}><Btn full onClick={()=>go("topup")} sx={{flex:1}}>{Z.dn} Recharger</Btn><Btn v="s" full onClick={()=>{}} sx={{flex:1}}>{Z.gear} Gérer</Btn></div>{[{t:"Paiement magasin",d:"Tous les marchands Mastercard"},{t:"Achats en ligne",d:"Tous les sites e-commerce"},{t:"Cashback 5%",d:"Sur tous vos achats"},{t:"Retrait ATM",d:"Distributeurs partenaires"}].map((b,i)=><div key={i} style={{display:"flex",gap:12,padding:"12px 16px",background:C.card,borderRadius:14,marginBottom:6,border:`1px solid ${C.brdL}`}}><div style={{width:36,height:36,borderRadius:10,background:C.blueL,display:"flex",alignItems:"center",justifyContent:"center",color:C.blue}}>{Z.shield}</div><div><div style={{fontSize:13,fontWeight:600,color:C.t1}}>{b.t}</div><div style={{fontSize:11,color:C.t3}}>{b.d}</div></div></div>)}</Scroll>;}
function SNBL({go}){const plans=[{name:"Smartphone",target:150000,monthly:25000,dur:"6 mois",partner:"Airtel Shop",progress:60},{name:"Électroménager",target:300000,monthly:30000,dur:"10 mois",partner:"Shoprite",progress:20}];return <Scroll><Hdr title="Save Now, Buy Later" onBack={()=>go("back")}/><div style={{background:`linear-gradient(135deg,${C.blue},${C.blueD})`,borderRadius:20,padding:"18px 20px",marginBottom:16}}><div style={{fontSize:16,fontWeight:800,color:"#fff"}}>Épargnez d'abord</div><div style={{fontSize:12,color:"rgba(255,255,255,0.7)"}}>Achetez sans dette. 0% d'intérêt.</div></div>{plans.map((p,i)=><div key={i} style={{background:C.card,borderRadius:20,padding:18,marginBottom:12,border:`1px solid ${C.brd}`}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><div><div style={{fontSize:15,fontWeight:700,color:C.t0}}>{p.name}</div><div style={{fontSize:12,color:C.t3}}>{p.partner} · {p.dur}</div></div><div style={{textAlign:"right"}}><div style={{fontSize:16,fontWeight:800,color:C.gold}}>{fm(p.target)} F</div><div style={{fontSize:10,color:C.t3}}>{fm(p.monthly)} F/mois</div></div></div>{p.progress>0&&<div><div style={{background:C.bg,borderRadius:4,height:6,overflow:"hidden",marginBottom:4}}><div style={{width:`${p.progress}%`,height:"100%",background:`linear-gradient(90deg,${C.blue},${C.gold})`}}/></div><div style={{fontSize:11,color:C.t3,textAlign:"right"}}>{p.progress}%</div></div>}<Btn full onClick={()=>go("ok")} sx={{padding:"10px 20px",fontSize:13,marginTop:8}}>{p.progress>0?"Cotiser":"Commencer"}</Btn></div>)}</Scroll>;}

export { Marketplace, KYC, CreditScore, KoloCard, SNBL };
