import { useState } from "react";
import { C, fm } from "../theme";
import { Z } from "../icons";
import { Btn, Av, Hdr, Bdg, Inp, Scroll, MenuRow, Toggle } from "../components";
import { NOTIFS, FAQS, SAV, RCPT } from "../data";

function Notif({go}){const im={warn:{bg:C.orangeL,c:C.orange},"in":{bg:C.greenL,c:C.green},gift:{bg:C.purpleL,c:C.purple},add:{bg:C.blueL,c:C.blue},pen:{bg:C.redL,c:C.red}};
return <Scroll><Hdr title="Notifications" onBack={()=>go("back")}/>{NOTIFS.map(n=>{const ic=im[n.tp]||im.warn;return <div key={n.id} style={{display:"flex",gap:12,padding:"14px 16px",background:C.card,borderRadius:16,marginBottom:8,border:`1px solid ${n.rd?C.brdL:C.blue+"20"}`,opacity:n.rd?.6:1}}><div style={{width:42,height:42,borderRadius:12,background:ic.bg,display:"flex",alignItems:"center",justifyContent:"center",color:ic.c,flexShrink:0}}>{Z.bell}</div><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600,color:C.t1}}>{n.tt}</div><div style={{fontSize:12,color:C.t3,marginTop:2}}>{n.ds}</div><div style={{fontSize:11,color:C.t4,marginTop:4}}>{n.tm}</div></div></div>;})}</Scroll>;}

// ── Profile/Security/Settings ──
function EditProfile({go}){return <Scroll><Hdr title="Modifier le profil" onBack={()=>go("back")}/><div style={{textAlign:"center",marginBottom:24}}><Av ini="JT" sz={80} col={C.blue}/></div><Inp label="Nom" ph="Joeldy Tsina" val="Joeldy Tsina" set={()=>{}}/><Inp label="Téléphone" ph="+242 06 466 3469" val="+242 06 466 3469" set={()=>{}}/><Inp label="Email" ph="joeldytsina94@gmail.com" val="joeldytsina94@gmail.com" set={()=>{}}/><Btn full onClick={()=>go("back")}>Enregistrer</Btn></Scroll>;}
function Sec({go}){return <Scroll><Hdr title="Sécurité" onBack={()=>go("back")}/><MenuRow icon={Z.lock} label="Changer le PIN" onClick={()=>go("ok")}/><MenuRow icon={Z.lock} label="Changer le mot de passe" onClick={()=>go("ok")}/><MenuRow icon={Z.shield} label="2FA" right={<span style={{fontSize:12,fontWeight:700,color:C.green}}>Activé</span>}/><MenuRow icon={Z.phone} label="Biométrie" right={<span style={{fontSize:12,fontWeight:700,color:C.green}}>Activé</span>}/></Scroll>;}
function Settings({go}){const[n,sN]=useState(true);const[b,sB]=useState(true);return <Scroll><Hdr title="Paramètres" onBack={()=>go("back")}/>{[{l:"Notifications push",v:n,s:sN},{l:"Biométrie",v:b,s:sB}].map((t,i)=><div key={i} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"16px 18px",background:C.card,borderRadius:16,marginBottom:8,border:`1px solid ${C.brdL}`}}><span style={{fontSize:14,color:C.t1}}>{t.l}</span><Toggle v={t.v} set={t.s}/></div>)}<MenuRow icon={Z.shield} label="Sécurité" onClick={()=>go("sec")}/><MenuRow icon={Z.globe} label="Langue" onClick={()=>go("lang")}/><MenuRow icon={Z.help} label="FAQ" onClick={()=>go("faq")}/><div style={{marginTop:20}}><button onClick={()=>go("login")} style={{width:"100%",padding:"14px",borderRadius:50,border:`1.5px solid ${C.red}`,background:"none",color:C.red,fontSize:14,fontWeight:600,cursor:"pointer"}}>Se déconnecter</button></div></Scroll>;}
function Lang({go}){return <Scroll><Hdr title="Langue" onBack={()=>go("back")}/>{[{n:"Français",f:"FR",a:true},{n:"Lingala",f:"LN",a:false},{n:"English",f:"EN",a:false}].map(l=><div key={l.f} style={{display:"flex",alignItems:"center",gap:14,padding:"16px",background:C.card,borderRadius:16,marginBottom:8,border:`1.5px solid ${l.a?C.blue:C.brdL}`,cursor:"pointer"}}><div style={{width:36,height:36,borderRadius:10,background:l.a?C.blueL:C.bg,display:"flex",alignItems:"center",justifyContent:"center",fontSize:14,fontWeight:700,color:l.a?C.blue:C.t3}}>{l.f}</div><span style={{flex:1,fontSize:14,fontWeight:600,color:C.t1}}>{l.n}</span>{l.a&&<div style={{width:20,height:20,borderRadius:10,background:C.blue,display:"flex",alignItems:"center",justifyContent:"center"}}>{Z.okW}</div>}</div>)}</Scroll>;}
function FAQ({go}){const[o,setO]=useState(null);return <Scroll><Hdr title="FAQ" onBack={()=>go("back")}/>{FAQS.map((f,i)=><div key={i} style={{background:C.card,borderRadius:16,marginBottom:8,border:`1px solid ${C.brdL}`,overflow:"hidden"}}><button onClick={()=>setO(o===i?null:i)} style={{display:"flex",alignItems:"center",justifyContent:"space-between",padding:"16px",width:"100%",background:"none",border:"none",cursor:"pointer",textAlign:"left"}}><span style={{fontSize:14,fontWeight:600,color:C.t1,flex:1}}>{f.q}</span><span style={{color:C.t3,transform:o===i?"rotate(90deg)":"none",transition:"0.2s"}}>{Z.fwd}</span></button>{o===i&&<div style={{padding:"0 16px 16px",fontSize:13,color:C.t2,lineHeight:1.5}}>{f.a}</div>}</div>)}</Scroll>;}

// ── Create/Join/Invite/QR/Remind/Savings/Receipts ──
function CreateCircle({go}){const[name,setName]=useState("");const[amt,setAmt]=useState("");return <Scroll><Hdr title="Créer un cercle" onBack={()=>go("back")}/><Inp label="Nom" ph="Ex: Cercle Famille" val={name} set={setName}/><Inp label="Montant/tour (FCFA)" ph="25000" val={amt} set={setAmt} type="number"/><div style={{marginBottom:16}}><label style={{fontSize:13,fontWeight:600,color:C.t2,marginBottom:6,display:"block"}}>Fréquence</label><div style={{display:"flex",gap:8}}>{["Hebdo","Bi-mensuel","Mensuel"].map(f=><button key={f} style={{flex:1,padding:"12px 0",borderRadius:12,border:"none",cursor:"pointer",background:f==="Mensuel"?C.blue:C.card,color:f==="Mensuel"?"#fff":C.t2,fontSize:13,fontWeight:600}}>{f}</button>)}</div></div><Btn full onClick={()=>go("ok")} dis={!name||!amt}>Créer</Btn></Scroll>;}
function JoinCircle({go}){const[code,setCode]=useState("");return <Scroll><Hdr title="Rejoindre" onBack={()=>go("back")}/><div style={{textAlign:"center",marginBottom:32}}><div style={{width:60,height:60,borderRadius:20,background:C.blueL,display:"inline-flex",alignItems:"center",justifyContent:"center",marginBottom:16,color:C.blue}}>{Z.link}</div><h3 style={{fontSize:18,fontWeight:700,color:C.t0}}>Code d'invitation</h3></div><Inp label="Code" ph="ELITE2026" val={code} set={setCode}/><Btn full onClick={()=>go("ok")} dis={!code}>Rejoindre</Btn></Scroll>;}
function Invite({go}){return <Scroll><Hdr title="Inviter" onBack={()=>go("back")}/><div style={{background:C.card,borderRadius:16,padding:20,border:`1px solid ${C.brd}`,textAlign:"center",marginBottom:20}}><div style={{fontSize:24,fontWeight:800,color:C.blue,letterSpacing:2,marginBottom:12}}>ELITE2026</div><Btn v="s" full>{Z.copy} Copier</Btn></div>{["WhatsApp","SMS","Lien"].map((m,i)=><button key={i} style={{display:"flex",alignItems:"center",gap:14,padding:"14px 16px",width:"100%",background:C.card,borderRadius:12,marginBottom:8,border:`1px solid ${C.brdL}`,cursor:"pointer"}}><div style={{width:36,height:36,borderRadius:10,background:C.blueL,display:"flex",alignItems:"center",justifyContent:"center",color:C.blue,fontWeight:700,fontSize:14}}>{m[0]}</div><span style={{flex:1,fontSize:14,color:C.t1}}>Inviter via {m}</span><span style={{color:C.t4}}>{Z.fwd}</span></button>)}</Scroll>;}
function QR({go}){const[tab,setTab]=useState("my");return <Scroll><Hdr title="QR Code" onBack={()=>go("back")}/>
<div style={{display:"flex",background:C.card,borderRadius:50,padding:3,marginBottom:20,border:`1px solid ${C.brd}`}}>{[{k:"my",l:"Mon QR"},{k:"scan",l:"Scanner"}].map(t=><button key={t.k} onClick={()=>setTab(t.k)} style={{flex:1,padding:"10px 0",borderRadius:50,border:"none",background:tab===t.k?C.blue:"transparent",color:tab===t.k?"#fff":C.t3,fontSize:13,fontWeight:600,cursor:"pointer"}}>{t.l}</button>)}</div>
{tab==="my"?<div style={{textAlign:"center"}}>
<div style={{background:C.card,borderRadius:24,padding:32,border:`1px solid ${C.brd}`,display:"inline-block",marginBottom:20}}>
<div style={{width:200,height:200,background:C.navy,borderRadius:16,display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 16px",position:"relative",overflow:"hidden"}}>
<div style={{width:170,height:170,background:"#fff",borderRadius:12,display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr 1fr",gridTemplateRows:"1fr 1fr 1fr 1fr 1fr",gap:4,padding:12}}>
{[1,1,1,0,1, 0,0,1,0,0, 1,0,1,0,1, 0,1,0,1,0, 1,0,1,1,1].map((n,i)=><div key={i} style={{background:i===12?C.blue:n?C.navy:"transparent",borderRadius:i===12?4:2}}/>)}
</div>
</div>
<div style={{fontSize:18,fontWeight:700,color:C.t0}}>Joeldy Tsina</div>
<div style={{fontSize:13,color:C.t3,marginTop:4}}>+242 06 466 3469</div>
<div style={{fontSize:12,color:C.kolo,fontWeight:600,marginTop:8,background:C.koloL,padding:"4px 12px",borderRadius:20,display:"inline-block"}}>Kolo Pay</div>
</div>
<div style={{display:"flex",gap:8}}>
<Btn v="s" full sx={{flex:1}}>{Z.copy} Copier</Btn>
<Btn full sx={{flex:1}}>{Z.send} Partager</Btn>
</div>
<div style={{marginTop:16,fontSize:12,color:C.t3}}>Scannez ce QR pour recevoir un paiement via Kolo Pay, MTN ou Airtel Money</div>
</div>
:<div>
<div style={{width:"100%",height:300,background:C.card,borderRadius:24,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",border:`2px dashed ${C.blue}`,marginBottom:20,position:"relative",overflow:"hidden"}}>
<div style={{position:"absolute",inset:40,border:`3px solid ${C.blue}`,borderRadius:16,opacity:.3}}/>
<div style={{position:"absolute",top:40,left:40,width:24,height:24,borderTop:`4px solid ${C.blue}`,borderLeft:`4px solid ${C.blue}`,borderRadius:"4px 0 0 0"}}/>
<div style={{position:"absolute",top:40,right:40,width:24,height:24,borderTop:`4px solid ${C.blue}`,borderRight:`4px solid ${C.blue}`,borderRadius:"0 4px 0 0"}}/>
<div style={{position:"absolute",bottom:40,left:40,width:24,height:24,borderBottom:`4px solid ${C.blue}`,borderLeft:`4px solid ${C.blue}`,borderRadius:"0 0 0 4px"}}/>
<div style={{position:"absolute",bottom:40,right:40,width:24,height:24,borderBottom:`4px solid ${C.blue}`,borderRight:`4px solid ${C.blue}`,borderRadius:"0 0 4px 0"}}/>
<div style={{color:C.blue,marginBottom:12}}>{Z.cam}</div>
<div style={{fontSize:14,fontWeight:600,color:C.t1}}>Pointez la caméra</div>
<div style={{fontSize:12,color:C.t3,marginTop:4}}>vers un QR Likelemba</div>
</div>
<Btn v="s" full onClick={()=>setTab("my")}>Afficher mon QR</Btn>
</div>}
</Scroll>;}
function Remind({go}){const up=MEM.filter(m=>!m.ok);return <Scroll><Hdr title="Rappel" onBack={()=>go("back")}/><div style={{background:C.orangeL,borderRadius:16,padding:"14px 18px",marginBottom:18,border:`1px solid ${C.orange}20`}}><div style={{fontSize:13,fontWeight:700,color:C.orange}}>{up.length} en attente</div></div>{MEM.map(m=><div key={m.id} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 16px",background:C.card,borderRadius:16,marginBottom:6,border:`1px solid ${C.brdL}`,opacity:m.ok?.5:1}}><Av ini={m.i} sz={40}/><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600,color:C.t1}}>{m.n}</div></div><Bdg s={m.ok?"paid":"pending"}/></div>)}<div style={{marginTop:16}}><Btn full onClick={()=>go("ok")}>Envoyer le rappel</Btn></div></Scroll>;}
function Sav({go}){return <Scroll><Hdr title="Objectifs d'épargne" onBack={()=>go("back")}/>{SAV.map(s=><div key={s.id} style={{background:C.card,borderRadius:16,padding:"16px 18px",marginBottom:10,border:`1px solid ${C.brdL}`}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><span style={{fontSize:14,fontWeight:600,color:C.t1}}>{s.n}</span><span style={{fontSize:13,fontWeight:700,color:s.sv>=s.tg?C.green:C.gold}}>{fm(s.sv)}/{fm(s.tg)}</span></div><div style={{background:C.bg,borderRadius:4,height:6,overflow:"hidden"}}><div style={{width:`${Math.min(s.sv/s.tg*100,100)}%`,height:"100%",background:s.cl,borderRadius:4}}/></div></div>)}</Scroll>;}
function Rcpt({go}){return <Scroll><Hdr title="Reçus" onBack={()=>go("back")}/>{RCPT.map(r=><div key={r.id} style={{display:"flex",alignItems:"center",gap:12,padding:16,background:C.card,borderRadius:16,marginBottom:8,border:`1px solid ${C.brdL}`}}><div style={{width:42,height:42,borderRadius:12,background:C.blueL,display:"flex",alignItems:"center",justifyContent:"center",color:C.blue}}>{Z.doc}</div><div style={{flex:1}}><div style={{fontSize:14,fontWeight:600,color:C.t1}}>{r.c}</div><div style={{fontSize:12,color:C.t3}}>{r.r} · {r.d}</div></div><div style={{textAlign:"right"}}><div style={{fontSize:14,fontWeight:700,color:C.gold}}>{fm(r.a)} F</div><Bdg s={r.s}/></div></div>)}</Scroll>;}

export { Notif, EditProfile, Sec, Settings, Lang, FAQ, Sav, Rcpt };
