import { useState, useRef } from "react";
import { C, fm } from "../theme";
import { Z } from "../icons";
import { Btn, Hdr, Av, Scroll } from "../components";

function Lamu({go}){const[msg,setMsg]=useState("");const[msgs,setMsgs]=useState([{id:1,from:"lamu",text:"Mbote ! Je suis Lamu, votre assistant. Je peux vous aider avec vos cercles, votre score crédit, ou toute question."}]);const ref=useRef(null);
const doSend=()=>{if(!msg.trim())return;const u={id:Date.now(),from:"me",text:msg.trim()};const bot={id:Date.now()+1,from:"lamu",text:"Merci pour votre question ! Je vous recommande de consulter votre score crédit (85/100) pour voir vos options. Vous pouvez aussi rejoindre un cercle public pour maximiser votre épargne."};setMsgs(p=>[...p,u,bot]);setMsg("");setTimeout(()=>{if(ref.current)ref.current.scrollTop=ref.current.scrollHeight;},50);};
return <div style={{height:"100%",display:"flex",flexDirection:"column",background:C.bg}}><div style={{padding:"12px 18px"}}><Hdr title="Lamu AI" onBack={()=>go("back")}/></div><div ref={ref} style={{flex:1,overflowY:"auto",padding:"0 18px 12px"}}>{msgs.map(m=><div key={m.id} style={{display:"flex",justifyContent:m.from==="me"?"flex-end":"flex-start",marginBottom:10}}>{m.from==="lamu"&&<div style={{width:28,height:28,borderRadius:14,background:`linear-gradient(135deg,${C.blue},${C.kolo})`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,color:"#fff",fontWeight:700,flexShrink:0,marginRight:6}}>L</div>}<div style={{maxWidth:"80%",padding:"12px 16px",borderRadius:16,borderTopLeftRadius:m.from==="me"?16:4,borderTopRightRadius:m.from==="me"?4:16,background:m.from==="me"?C.blue:C.card,color:m.from==="me"?"#fff":C.t1,fontSize:13,lineHeight:1.5,whiteSpace:"pre-line",boxShadow:m.from==="me"?"none":C.sh}}>{m.text}</div></div>)}</div><div style={{padding:"8px 18px 16px",background:C.card,borderTop:`1px solid ${C.brd}`}}><div style={{display:"flex",gap:8}}><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==="Enter"&&doSend()} placeholder="Posez une question..." style={{flex:1,padding:"12px 16px",borderRadius:50,border:`1px solid ${C.brd}`,background:C.bg,outline:"none",fontSize:14,color:C.t0}}/><button onClick={doSend} style={{width:44,height:44,borderRadius:22,background:`linear-gradient(135deg,${C.blue},${C.kolo})`,border:"none",cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",flexShrink:0}}>{Z.send}</button></div></div></div>;}

// ── Group Goals ──
function GroupGoals({go}){const goals=[{n:"Mariage de Grace",target:2000000,saved:750000,members:8,col:C.gold},{n:"Excursion Pointe-Noire",target:500000,saved:350000,members:12,col:C.green}];return <Scroll><Hdr title="Objectifs de groupe" onBack={()=>go("back")}/>{goals.map((g,i)=>{const pct=Math.round(g.saved/g.target*100);return <div key={i} style={{background:C.card,borderRadius:20,padding:18,marginBottom:12,border:`1px solid ${C.brd}`}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><div><div style={{fontSize:15,fontWeight:700,color:C.t0}}>{g.n}</div><div style={{fontSize:12,color:C.t3}}>{g.members} participants</div></div><div style={{fontSize:16,fontWeight:800,color:C.gold}}>{pct}%</div></div><div style={{display:"flex",justifyContent:"space-between",marginBottom:6,fontSize:12,color:C.t3}}><span>{fm(g.saved)} / {fm(g.target)} F</span></div><div style={{background:C.bg,borderRadius:4,height:8,overflow:"hidden",marginBottom:12}}><div style={{width:`${pct}%`,height:"100%",background:`linear-gradient(90deg,${g.col},${C.gold})`}}/></div><Btn full onClick={()=>go("contribute")} sx={{padding:"10px 20px",fontSize:13}}>Contribuer</Btn></div>;})}</Scroll>;}

// ════════════ NEW FEATURES ════════════


export { Lamu, GroupGoals };
